# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideStudentMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'GuideStudentMap',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pass', models.CharField(max_length=150)),
                ('user_role', models.IntegerField(default=-1)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='VMS_Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_sem', models.CharField(choices=[('odd', 'odd'), ('even', 'even')], max_length=5)),
            ],
            options={
                'db_table': 'VMS_Session',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='degree_name',
            field=models.CharField(default='Msc', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='allocated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='is_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Course'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Faculty'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='empid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Faculty'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='rollno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Student'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.VMS_Session'),
        ),
        migrations.AddField(
            model_name='guidestudentmap',
            name='tutor',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.User'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('user_id', 'user_role')]),
        ),
        migrations.AlterUniqueTogether(
            name='guidestudentmap',
            unique_together=set([('session', 'empid', 'rollno')]),
        ),
    ]
