# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-21 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0002_auto_20161222_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='email_id',
            field=models.EmailField(default='Invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='batch',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faculty',
            name='email_id',
            field=models.EmailField(default='Invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.EmailField(default='Invalid', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor_email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='vms_session',
            name='session_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='address_short_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='domain_key_word',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='postal_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='project_category',
            field=models.CharField(blank=True, choices=[('Industry', 'Industry Project'), ('Research', 'Institution/Research Project')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='project_title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
