# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0003_auto_20161222_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Course')),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Faculty')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.VMS_Session')),
            ],
            options={
                'db_table': 'Tutor',
            },
        ),
        migrations.RenameField(
            model_name='guidestudentmap',
            old_name='empid',
            new_name='guide',
        ),
        migrations.RenameField(
            model_name='guidestudentmap',
            old_name='rollno',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='guidestudentmap',
            unique_together=set([('session', 'guide', 'student')]),
        ),
        migrations.AlterUniqueTogether(
            name='tutor',
            unique_together=set([('session', 'empId', 'Course')]),
        ),
    ]
