# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-23 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0005_auto_20161223_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidestudentmap',
            name='tutor',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='VivaManagementSystem.Tutor'),
        ),
    ]
