# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0006_auto_20161223_0836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course_id',
            new_name='course',
        ),
    ]
