# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-28 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0008_course_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms_session',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
