# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-30 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VivaManagementSystem', '0010_auto_20161230_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='tutor_id',
            new_name='tutor',
        ),
    ]
